# Generated by Django 5.0.1 on 2024-01-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remover', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rmbg_img',
            field=models.ImageField(blank=True, null=True, upload_to='images_rmbg/'),
        ),
    ]
