# Generated by Django 5.0.1 on 2024-01-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remover', '0002_alter_image_rmbg_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('rmbg_img', models.ImageField(blank=True, null=True, upload_to='images_rmbg/')),
            ],
        ),
    ]
