# Generated by Django 5.0.1 on 2024-01-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remover', '0003_image2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image2',
        ),
    ]
